// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Omino.Infra.Master;
using System.Collections.Generic;
using System;
using Omino.Infra.Master.Tables;

namespace Omino.Infra.Master
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<CharacterData> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new CharacterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.PartyDataTable
            
            );
        }

        public void RemoveCharacterData(uint[] keys)
        {
            var data = RemoveCore(memory.CharacterDataTable.GetRawDataUnsafe(), keys, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new CharacterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.PartyDataTable
            
            );
        }

        public void Diff(CharacterData[] addOrReplaceData)
        {
            var data = DiffCore(memory.CharacterDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new CharacterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.PartyDataTable
            
            );
        }

        public void ReplaceAll(System.Collections.Generic.IList<PartyData> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new PartyDataTable(newData);
            memory = new MemoryDatabase(
                memory.CharacterDataTable,
                table
            
            );
        }

        public void RemovePartyData(uint[] keys)
        {
            var data = RemoveCore(memory.PartyDataTable.GetRawDataUnsafe(), keys, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new PartyDataTable(newData);
            memory = new MemoryDatabase(
                memory.CharacterDataTable,
                table
            
            );
        }

        public void Diff(PartyData[] addOrReplaceData)
        {
            var data = DiffCore(memory.PartyDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            var table = new PartyDataTable(newData);
            memory = new MemoryDatabase(
                memory.CharacterDataTable,
                table
            
            );
        }

    }
}