// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Omino.Infra.Master;
using System.Collections.Generic;
using System;
using Omino.Infra.Master.Tables;

namespace Omino.Infra.Master
{
   public sealed class DatabaseBuilder : DatabaseBuilderBase
   {
        public DatabaseBuilder() : this(null) { }
        public DatabaseBuilder(MessagePack.IFormatterResolver resolver) : base(resolver) { }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<CharacterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            return this;
        }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<PartyData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<uint>.Default);
            return this;
        }

    }
}