// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Omino.Infra.Master;
using System.Collections.Generic;
using System;
using Omino.Infra.Master.Tables;

namespace Omino.Infra.Master
{
   public sealed class MemoryDatabase : MemoryDatabaseBase
   {
        public CharacterDataTable CharacterDataTable { get; private set; }
        public PartyDataTable PartyDataTable { get; private set; }

        public MemoryDatabase(
            CharacterDataTable CharacterDataTable,
            PartyDataTable PartyDataTable
        )
        {
            this.CharacterDataTable = CharacterDataTable;
            this.PartyDataTable = PartyDataTable;
        }

        public MemoryDatabase(byte[] databaseBinary, bool internString = true, MessagePack.IFormatterResolver formatterResolver = null)
            : base(databaseBinary, internString, formatterResolver)
        {
        }

        protected override void Init(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options)
        {
            this.CharacterDataTable = ExtractTableData<CharacterData, CharacterDataTable>(header, databaseBinary, options, xs => new CharacterDataTable(xs));
            this.PartyDataTable = ExtractTableData<PartyData, PartyDataTable>(header, databaseBinary, options, xs => new PartyDataTable(xs));
        }

        public ImmutableBuilder ToImmutableBuilder()
        {
            return new ImmutableBuilder(this);
        }

        public DatabaseBuilder ToDatabaseBuilder()
        {
            var builder = new DatabaseBuilder();
            builder.Append(this.CharacterDataTable.GetRawDataUnsafe());
            builder.Append(this.PartyDataTable.GetRawDataUnsafe());
            return builder;
        }

        public DatabaseBuilder ToDatabaseBuilder(MessagePack.IFormatterResolver resolver)
        {
            var builder = new DatabaseBuilder(resolver);
            builder.Append(this.CharacterDataTable.GetRawDataUnsafe());
            builder.Append(this.PartyDataTable.GetRawDataUnsafe());
            return builder;
        }

        public ValidateResult Validate()
        {
            var result = new ValidateResult();
            var database = new ValidationDatabase(new object[]
            {
                CharacterDataTable,
                PartyDataTable,
            });

            ((ITableUniqueValidate)CharacterDataTable).ValidateUnique(result);
            ValidateTable(CharacterDataTable.All, database, "Id", CharacterDataTable.PrimaryKeySelector, result);
            ((ITableUniqueValidate)PartyDataTable).ValidateUnique(result);
            ValidateTable(PartyDataTable.All, database, "Id", PartyDataTable.PrimaryKeySelector, result);

            return result;
        }

        static MasterMemory.Meta.MetaDatabase metaTable;

        public static object GetTable(MemoryDatabase db, string tableName)
        {
            switch (tableName)
            {
                case "characters":
                    return db.CharacterDataTable;
                case "parties":
                    return db.PartyDataTable;
                
                default:
                    return null;
            }
        }

        public static MasterMemory.Meta.MetaDatabase GetMetaDatabase()
        {
            if (metaTable != null) return metaTable;

            var dict = new Dictionary<string, MasterMemory.Meta.MetaTable>();
            dict.Add("characters", Omino.Infra.Master.Tables.CharacterDataTable.CreateMetaTable());
            dict.Add("parties", Omino.Infra.Master.Tables.PartyDataTable.CreateMetaTable());

            metaTable = new MasterMemory.Meta.MetaDatabase(dict);
            return metaTable;
        }
    }
}